### ISSUE TITLE
Feature Request: Extend syncStatusBar option

### ISSUE THREAD

**Issue by NePheus** [aparajita/capacitor-dark-mode#2]
Regarding the options 'syncStatusBar' it would be nice to have the ability to skip setting the background color (https://github.com/aparajita/capacitor-dark-mode/blob/main/src/base.ts#L163). In my case I set the status bar background on transparent on app start (StatusBar.setBackgroundColor({ color: '#00000000' }), because I am using my app in fullscreen (<item name="android:windowTranslucentNavigation">true</item>) but this plugin would override the color if I use the option syncStatusBar. So either a new option should be introduced to skip setting the background color and only set the style of the statusbar to change its text color, or the --background should also handle alpha channels.

I would prefer a new option to prevent an overhead of useless 'setBackgroundColor' calls in my case. In other cases the non alpha hex values should be enough. What do you think?

**Comment by aparajita** [comment]
I guess I could allow `syncStatusBar` to be either `true` (change text color and background) or `textOnly`.

**Comment by NePheus** [comment]
Hey aparajita,
do you have any news on this? :)

**Comment by aparajita** [comment]
Implemented in v3.1.0.
