### ISSUE TITLE
How to change the splash style

### ISSUE THREAD

**Issue by NePheus** [aparajita/capacitor-dark-mode#3]
I am still struggling with changing the splash theme persistently, independendly of the system setting. Inside my app, everything if working fine, also auto updating, when changing the system theme.

In my styles.xml I changed the parent themes to the DayNight variants, as also described in the capacitor 4 migration docs. I also added -night folders to change my splash appearance depending to the system theme. This is working good so far. But when I change the theme inside my app, I would like to also change the theme for the splash on the next app start, but unforunately it always takes the system settings. So I have something like a dark splash (system night mode) and then showing up the app in light (app day mode), but the splash should also be light here.

I tried to use [AppCompatDelegate.setDefaultNightMode()](https://developer.android.com/reference/androidx/appcompat/app/AppCompatDelegate#setDefaultNightMode(int)), but it has no effect, no matter where I call it (i.e. in override OnCreate before or after super call). I also created a capacitor plugin to calling it programmatically anywhere, but it doesnt change anything. But I also read, that calling this method, does not persistently change the behaviour, so it would be needed to call it on every start?! Do you have any clue how to solve this, or maybe also a way to integrate something to this plugin?

**Comment by aparajita** [comment]
We have no control over the splash screen, that happens at the system level and is always going to follow the system setting.

**Comment by NePheus** [comment]
That means that the setDefaultNightMode just sets the "current" theme but can never change the splash? Thats really unlucky :/ so its not possible to implement a consistent theme flow from splash to app. Really sad that google do not offer a solution for this in 2022...

**Comment by aparajita** [comment]
Splash screens are handled by the system, both on Android and iOS. Going forward, splash screens are going to be very different on Android, as they now have a standard system splash screen API which adds some features but also imposes some limitations.

My upcoming splash screen plugin allows you to display a splash screen on app resume, and you can set the background color. But on Android it is impossible to reliably display the splash before the app content appears. On iOS you can.
