### ISSUE TITLE
body class add optional add

### ISSUE THREAD

**Issue by productdevbook** [aparajita/capacitor-dark-mode#4]
Can you add a feature to turn off body adding feature? Thank you

**Comment by aparajita** [comment]
That is how this plugin works. The reason I made this plugin is using `@media` queries is not  reliable on Android, so the only other option is to add a class.

**Comment by productdevbook** [comment]
How about if you look at the html or body for control? or add such a feature. because use html. with tailwindcss

**Comment by aparajita** [comment]
I also use Tailwind. I think you have misunderstood how dark mode in Tailwind works. The `dark:` variant takes effect when **any** element earlier in the html tree has a `dark` class. No content can be earlier than `body`, so for the purposes of setting dark mode globally, adding the `dark` class to the `body` tag is no different than adding it to the `html` tag.

**Comment by productdevbook** [comment]
https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

unfortunately tailwind does not detect body with css

**Comment by aparajita** [comment]
The **examples** Tailwind gives set the class on the html element, but the documentation clearly states it can be anywhere earlier in the tree, and I did test it successfully on the body tag.
